# Generated by Django 5.2.8 on 2025-12-05 16:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_incidenttypedim_safetytip_stolenitemdim_userfeedback'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('high_crime', 'High Crime Rate'), ('recent_incident', 'Recent Incident'), ('warning', 'Warning')], max_length=50)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'area_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IMEIRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(db_index=True, max_length=20, unique=True)),
                ('phone_brand', models.CharField(blank=True, max_length=100)),
                ('phone_model', models.CharField(blank=True, max_length=100)),
                ('owner_name', models.CharField(blank=True, max_length=150)),
                ('owner_contact', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('stolen', 'Stolen'), ('recovered', 'Recovered'), ('flagged', 'Flagged')], default='stolen', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'IMEI Registries',
                'db_table': 'imei_registry',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='incidentfact',
            options={'ordering': ['-occurred_at']},
        ),
        migrations.RemoveField(
            model_name='incidentfact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='incidentfact',
            name='time',
        ),
        migrations.RemoveField(
            model_name='incidentfact',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='incidentfact',
            name='fir_document',
            field=models.FileField(blank=True, null=True, upload_to='fir_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='incidentfact',
            name='fir_filed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidentfact',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='incidentfact',
            name='occurred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentfact',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentfact',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='reported', max_length=20),
        ),
        migrations.AddField(
            model_name='incidentfact',
            name='stolen_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.stolenitemdim'),
        ),
        migrations.AddField(
            model_name='incidentfact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='incidentfact',
            name='value_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incidentfact',
            name='incident_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.incidenttypedim'),
        ),
        migrations.AlterField(
            model_name='incidentfact',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.locationdim'),
        ),
        migrations.AlterField(
            model_name='incidentfact',
            name='victim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.victimdim'),
        ),
        migrations.AddIndex(
            model_name='incidentfact',
            index=models.Index(fields=['occurred_at'], name='incident_fa_occurre_09ab25_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentfact',
            index=models.Index(fields=['location', 'occurred_at'], name='incident_fa_locatio_1eef41_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentfact',
            index=models.Index(fields=['incident_type', 'occurred_at'], name='incident_fa_inciden_d2276d_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentfact',
            index=models.Index(fields=['status'], name='incident_fa_status_609ca8_idx'),
        ),
        migrations.AlterModelTable(
            name='incidentfact',
            table='incident_fact',
        ),
        migrations.AddField(
            model_name='areaalert',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='areaalert',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.locationdim'),
        ),
        migrations.AddField(
            model_name='imeiregistry',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imei_records', to='reports.incidentfact'),
        ),
        migrations.AddField(
            model_name='imeiregistry',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imei_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
