# Generated by Django 5.2.8 on 2025-12-09 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_areaalert_imeiregistry_alter_incidentfact_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IMEICheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('location_info', models.JSONField(blank=True, null=True)),
                ('alert_sent', models.BooleanField(default=False)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imei_checks', to=settings.AUTH_USER_MODEL)),
                ('imei_registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_logs', to='reports.imeiregistry')),
            ],
            options={
                'db_table': 'imei_check_logs',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='StolenDeviceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('check_detected', 'Check Detected'), ('purchase_attempt', 'Purchase Attempt'), ('location_update', 'Location Update')], default='check_detected', max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('check_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.imeichecklog')),
                ('imei_registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='reports.imeiregistry')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stolen_device_alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
