# Generated by Django 5.2.8 on 2025-12-05 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_incidenttypedim_safetytip_stolenitemdim_userfeedback'),
        ('reports', '0002_areaalert_imeiregistry_alter_incidentfact_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeDim',
        ),
        migrations.RemoveField(
            model_name='locationdim',
            name='area',
        ),
        migrations.RemoveField(
            model_name='victimdim',
            name='cnic',
        ),
        migrations.RemoveField(
            model_name='victimdim',
            name='full_name',
        ),
        migrations.AddField(
            model_name='locationdim',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='locationdim',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locationdim',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locationdim',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locationdim',
            name='street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='victimdim',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='victimdim',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='victimdim',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='victimdim',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='victimdim',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='victimdim',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddIndex(
            model_name='locationdim',
            index=models.Index(fields=['city', 'district'], name='location_di_city_8545e5_idx'),
        ),
        migrations.AddIndex(
            model_name='locationdim',
            index=models.Index(fields=['latitude', 'longitude'], name='location_di_latitud_b5549e_idx'),
        ),
        migrations.AlterModelTable(
            name='locationdim',
            table='location_dim',
        ),
        migrations.AlterModelTable(
            name='victimdim',
            table='victim_dim',
        ),
        migrations.AddField(
            model_name='safetytip',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='stolenitemdim',
            index=models.Index(fields=['item_type'], name='stolen_item_item_ty_d0248c_idx'),
        ),
        migrations.AddIndex(
            model_name='stolenitemdim',
            index=models.Index(fields=['imei'], name='stolen_item_imei_627d5f_idx'),
        ),
        migrations.AddIndex(
            model_name='stolenitemdim',
            index=models.Index(fields=['license_plate'], name='stolen_item_license_dd3699_idx'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
